/**
 * Weekly Digest Generator
 *
 * Reads items first seen in the last 7 days from the hub.db, applies the
 * star floor, classifies by category, and writes a markdown digest to
 * ~/ai-intelligence-hub/digests/weekly-YYYY-MM-DD.md.
 *
 * Star-floor SQL filter is enforced in db.getItemsFirstSeenSince. This
 * module focuses on classification + markdown formatting.
 */
const fs = require('fs');
const path = require('path');
const db = require('../database/db');
const { loadPool, recommendFromPool, parseMeta } = require('./recommend');

const DIGESTS_DIR = path.join(__dirname, '..', 'digests');

// Topic-set classification. First match wins. Order matters.
const CATEGORY_MATCHERS = [
  { id: 'claude-code', label: '🤖 Claude Code', topics: ['claude-code', 'claude'] },
  { id: 'mcp', label: '🔌 MCP (Model Context Protocol)', topics: ['mcp', 'model-context-protocol'] },
  { id: 'adk', label: '🛠️  ADK / Agent SDK', topics: ['adk', 'agent-development-kit', 'agent-sdk'] },
  { id: 'agent-fw', label: '🧠 Agent Frameworks', topics: ['agent-framework', 'ai-agents', 'multi-agent', 'autogen', 'langgraph', 'crewai'] },
  { id: 'video-ai', label: '🎬 Video / Generative UI', topics: ['remotion', 'video-generation', 'generative-ui', 'animation'] },
  { id: 'rag', label: '📚 RAG / Retrieval', topics: ['rag', 'retrieval', 'embeddings', 'vector-database'] },
  { id: 'eval', label: '📏 Evaluation / Tooling', topics: ['llm-evaluation', 'llm-tools', 'llm-ops', 'prompt-engineering'] },
];

function classify(item) {
  const meta = parseMeta(item);
  const repoTopics = (meta.topics || []).map((t) => String(t).toLowerCase());
  const description = (item.description || '').toLowerCase();
  const title = (item.title || '').toLowerCase();

  if (meta.category_hint) {
    const found = CATEGORY_MATCHERS.find((c) => c.id === meta.category_hint);
    if (found) return found;
  }

  for (const cat of CATEGORY_MATCHERS) {
    for (const t of cat.topics) {
      if (repoTopics.includes(t) || description.includes(t) || title.includes(t)) {
        return cat;
      }
    }
  }
  return { id: 'other', label: '✨ Other', topics: [] };
}


function isRisingStar(item) {
  const meta = parseMeta(item);
  if (!meta.created_at) return false;
  const ageDays = (Date.now() - new Date(meta.created_at).getTime()) / 86400000;
  return ageDays <= 90 && (item.stars || 0) >= 200 && (item.stars || 0) < 5000;
}

// mdLinkText lives in ./digest-sections — the canonical escaper for every
// markdown link built from a third-party title, in this file (renderItem,
// renderTLDR, formatProjectSections below) AND in digest-sections.js's own
// ground-truth renderer. See that file for the full rationale.
const { mdLinkText, formatGroundTruthSection } = require('./digest-sections');

function renderItem(item) {
  const meta = parseMeta(item);
  const stars = (item.stars || 0).toLocaleString();
  const reason = meta.match_reason || meta.perplexity_summary || meta.discovery_strategy || '';
  const lang = meta.language ? ` · ${meta.language}` : '';
  const desc = (item.description || '').replace(/\s+/g, ' ').trim().slice(0, 200);
  return `- **[${mdLinkText(item.title)}](${item.url})** · ${stars}★${lang}\n  - ${desc}${desc ? '\n  - ' : ''}_${reason}_`;
}

function renderTLDR(items) {
  const top = items.slice(0, 5);
  if (top.length === 0) return '_No items met the star floor this week._';
  return top
    .map((it, i) => {
      const stars = (it.stars || 0).toLocaleString();
      return `${i + 1}. **[${mdLinkText(it.title)}](${it.url})** — ${stars}★`;
    })
    .join('\n');
}

function buildDigestStructure({ items, runDate }) {
  const buckets = {};
  for (const cat of CATEGORY_MATCHERS) buckets[cat.id] = { cat, items: [] };
  buckets.other = { cat: { id: 'other', label: '✨ Other', topics: [] }, items: [] };

  const rising = [];
  for (const item of items) {
    const cat = classify(item);
    buckets[cat.id]?.items.push(item);
    if (isRisingStar(item)) rising.push(item);
  }

  const perCategory = {};
  for (const id of Object.keys(buckets)) {
    perCategory[id] = buckets[id].items.length;
  }

  return {
    buckets,
    rising,
    runDate,
    totals: {
      totalItems: items.length,
      perCategory,
      risingCount: rising.length,
    },
  };
}

function formatDigest({ items, runDate, channelStats = {} }) {
  const { buckets, rising } = buildDigestStructure({ items, runDate });

  const lines = [];
  lines.push(`# Weekly Claude Code Ecosystem Digest — ${runDate}`);
  lines.push('');
  lines.push(`> Items first seen in the last 7 days, filtered by star floor (≥1,000★ established / ≥200★ rising-star <90d).`);
  lines.push(`> Generated by AI Intelligence Hub — ${items.length} items across ${Object.values(buckets).filter((b) => b.items.length).length} categories.`);
  lines.push('');

  if (Object.keys(channelStats).length) {
    lines.push('**Channels run**: ' + Object.entries(channelStats).map(([k, v]) => `${k} (${v})`).join(' · '));
    lines.push('');
  }

  // TL;DR top 5
  lines.push('## TL;DR — Top 5');
  lines.push('');
  lines.push(renderTLDR(items));
  lines.push('');

  // Rising stars sub-section (always show, even if empty — signals the channel exists)
  lines.push('## 🌟 Rising Stars (last 90d, 200-5000★)');
  lines.push('');
  if (rising.length === 0) {
    lines.push('_No rising stars surfaced this week._');
  } else {
    for (const item of rising.slice(0, 8)) lines.push(renderItem(item));
  }
  lines.push('');

  // Per-category lists
  for (const cat of CATEGORY_MATCHERS) {
    const list = buckets[cat.id].items;
    if (list.length === 0) continue;
    lines.push(`## ${cat.label} (${list.length})`);
    lines.push('');
    for (const item of list) lines.push(renderItem(item));
    lines.push('');
  }

  // Other bucket only if non-trivial
  if (buckets.other.items.length > 0) {
    lines.push(`## ✨ Other (${buckets.other.items.length})`);
    lines.push('');
    for (const item of buckets.other.items) lines.push(renderItem(item));
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Star floor enforced. Generated ${new Date().toISOString()}._`);
  return lines.join('\n');
}

/**
 * "Adopted & tracked" — what changed upstream since the last digest.
 *
 * CHANGES ONLY. The tracker checks ~257 repos every day; listing them weekly
 * would be a wall nobody reads, and then the week something is archived reads
 * exactly like every other week. A quiet week says so in one sentence, which is
 * the whole point of having checked.
 *
 * Alarm count is stated even when it is zero, because "0 alarms" is a result and
 * an omitted section is an absence of one.
 */
/**
 * A `deleted` ALARM is a claim about the LAST probe, not a fact about the week.
 * When a later run finds the repo alive (http 200 - e.g. an HF model the old
 * GitHub-only probe 404'd on), the stale alarm is downgraded to a NOTE that
 * says so, instead of standing beside the run that cleared it. Anything short
 * of a 200 (404, 429, null) keeps the alarm: a rate limit is not proof of life.
 */
function dropClearedDeletions(events = [], rows = []) {
  const alive = new Set(rows.filter((r) => Number(r.http_status) === 200).map((r) => r.repo));
  return events.map((e) => {
    if (e.event !== 'deleted' || !alive.has(e.repo)) return e;
    return { ...e, event: 'cleared', severity: 'NOTE', to: '200 on re-probe (was 404)', to_value: '200 on re-probe (was 404)' };
  });
}

function formatTrackedSection({ events = [], checked = null, projectsByRepo = {} } = {}) {
  const lines = ['', '## 📡 Adopted & tracked — what changed upstream', ''];
  const scope = checked === null ? '' : ` across ${checked} repos we adopted, watch, or depend on`;

  const alarms = events.filter((e) => e.severity === 'ALARM');
  const warns = events.filter((e) => e.severity === 'WARN');
  const cleared = events.filter((e) => e.event === 'cleared');
  const notes = events.filter((e) => e.severity === 'NOTE' && e.event !== 'cleared');

  if (!events.length) {
    lines.push(`Nothing changed upstream this week — **0 alarms**${scope}.`, '');
    return lines.join('\n');
  }

  lines.push(
    `**${alarms.length} alarm${alarms.length === 1 ? '' : 's'}**, ` +
      `${notes.length} release${notes.length === 1 ? '' : 's'}, ` +
      `${warns.length} gone quiet${scope}` + (cleared.length ? `, ${cleared.length} cleared` : '') + '.',
    ''
  );

  const who = (repo) => {
    const ps = projectsByRepo[repo] || [];
    return ps.length ? ` — ${ps.join(', ')}` : '';
  };
  const label = { archived: 'ARCHIVED', deleted: 'DELETED', cleared: 'cleared (false alarm)', renamed: 'RENAMED', major_release: 'MAJOR', release: 'release', stale: 'quiet' };
  const render = (e) => {
    const arrow = e.to && e.event !== 'archived' ? ` → \`${e.to}\`` : '';
    return `- **${label[e.event] || e.event}** \`${e.repo}\`${arrow}${who(e.repo)}`;
  };

  if (alarms.length) {
    lines.push('### ⛔ Needs a look', '');
    for (const e of alarms) lines.push(render(e));
    lines.push('');
  }
  if (cleared.length) {
    lines.push('### ✅ Cleared — a later probe found them alive', '');
    for (const e of cleared) lines.push(render(e));
    lines.push('');
  }
  if (notes.length) {
    lines.push('### New versions', '');
    for (const e of notes) lines.push(`- \`${e.repo}\` ${e.from || '?'} → **${e.to}**${who(e.repo)}`);
    lines.push('');
  }
  if (warns.length) {
    lines.push(`### Gone quiet (no push in 180 days) — ${warns.length}`, '');
    for (const e of warns) lines.push(`- \`${e.repo}\`${who(e.repo)}`);
    lines.push('');
  }
  return lines.join('\n');
}

function formatProjectSections({ perProject = 5 } = {}) {
  let projects = [];
  try {
    projects = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'config', 'projects.json'), 'utf-8')).projects || [];
  } catch {
    return '';
  }
  const lines = ['', '## 🎯 Per-project suggestions (star floor 200, no forks/dupes)', ''];
  const pool = loadPool(db); // one read + parse for all projects
  for (const p of projects) {
    let recs;
    try {
      recs = recommendFromPool(pool, p.id, { limit: perProject });
    } catch (err) {
      lines.push(`### ${p.name} — error: ${err.message}`, '');
      continue;
    }
    lines.push(`### ${p.name} (${recs.discoveries.length} of ${recs.poolSize} candidates)`);
    if (!recs.discoveries.length) lines.push('- _no candidates above the floor yet_');
    for (const r of recs.discoveries) {
      const why = (r.relevance && r.relevance.matchReason) || '';
      lines.push(`- **[${mdLinkText(r.title)}](${r.url})** · ${(r.stars || 0).toLocaleString()}★${why ? ` — _${why}_` : ''}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * The ground-truth section reads the SAME pool the per-project section does,
 * so a dataset that reached the index reaches the digest without a second
 * fetch. Split out of generateDigest so that function stays under the
 * 50-line cap; a failure here becomes a visible section, never a thrown
 * error that would take the other five sections down with it.
 */
function buildGroundTruthDigestSection() {
  try {
    const { validateFeatures } = require('./ground-truth');
    const { buildLedger } = require('./ledger');
    const { readAllRadarRows, readDepRepos } = require('../routes/lib/hub-sources');
    const projects = JSON.parse(
      fs.readFileSync(path.join(__dirname, '..', 'config', 'projects.json'), 'utf-8')
    ).projects || [];
    // Fail closed on the real config before it is rendered into the digest —
    // the same gate routes/ground-truth.js runs before the page.
    validateFeatures(projects);
    // The near-miss log is part of the weekly picture, not a page-only extra:
    // it is the corpus for the next slot, and Monday is when anyone reads it.
    let nearMisses = [];
    try {
      nearMisses = db.nearMissStore ? db.nearMissStore.all({ limit: 200 }) : [];
    } catch (e) {
      nearMisses = [];
    }
    let ledgerRows = [];
    try {
      const { depRepos } = readDepRepos();
      ledgerRows = buildLedger({ radarRows: readAllRadarRows(), depRepos }).rows;
    } catch (e) {
      ledgerRows = [];
    }
    return formatGroundTruthSection(loadPool(db), projects, nearMisses, ledgerRows);
  } catch (err) {
    // Best-effort enrichment: a digest that fails to build is worse than one
    // missing a section, but a SILENT miss is worse than both - say it failed.
    return `\n## 🔬 External ground truth\n\n- _section failed: ${err.message}_\n`;
  }
}

async function generateDigest({ channelStats = {}, costUsd = 0, runtimeStartMs = Date.now() } = {}) {
  if (!fs.existsSync(DIGESTS_DIR)) fs.mkdirSync(DIGESTS_DIR, { recursive: true });

  const runDate = new Date().toISOString().slice(0, 10);
  const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString();

  const items = db.getItemsFirstSeenSince(sevenDaysAgo, { limit: 80 });

  // Upstream changes since the last digest — see formatTrackedSection.
  let tracked = '';
  try {
    const rows = db.tracked.all();
    const events = dropClearedDeletions(db.tracked.eventsSince(sevenDaysAgo), rows);
    const projectsByRepo = Object.fromEntries(rows.map((r) => [r.repo, r.projects]));
    // Rows retired from the pool stay in the table but are no longer checked;
    // counting them would overstate the sweep by exactly the retired set.
    tracked = formatTrackedSection({ events, checked: db.tracked.lastRunCount(), projectsByRepo });
  } catch (err) {
    // The digest is the delivery channel for five other sections; a tracker
    // problem must not take them down with it, but it must be visible.
    console.error(`[digest] tracked section failed: ${err.message}`);
    tracked = `\n## 📡 Adopted & tracked — what changed upstream\n\n_Unavailable this week: ${err.message}_\n`;
  }

  const groundTruth = buildGroundTruthDigestSection();
  const md = formatDigest({ items, runDate, channelStats }) + tracked + formatProjectSections() + groundTruth;

  const outPath = path.join(DIGESTS_DIR, `weekly-${runDate}.md`);
  fs.writeFileSync(outPath, md, 'utf-8');

  const runtimeMs = Date.now() - runtimeStartMs;
  db.insertWeeklyRun({
    run_date: runDate,
    item_count: items.length,
    channels_run: Object.keys(channelStats).join(','),
    runtime_ms: runtimeMs,
    cost_usd: costUsd,
  });

  return { digestPath: outPath, itemCount: items.length, runtimeMs };
}

module.exports = { generateDigest, formatDigest, formatProjectSections, formatGroundTruthSection, formatTrackedSection, dropClearedDeletions, buildDigestStructure, classify, isRisingStar, parseMeta };
