/**
 * Weekly Digest Generator
 *
 * Reads items first seen in the last 7 days from the hub.db, applies the
 * star floor, classifies by category, and writes a markdown digest to
 * ~/ai-intelligence-hub/digests/weekly-YYYY-MM-DD.md.
 *
 * Star-floor SQL filter is enforced in db.getItemsFirstSeenSince. This
 * module focuses on classification + markdown formatting.
 */
const fs = require('fs');
const path = require('path');
const db = require('../database/db');
const { loadPool, recommendFromPool, parseMeta } = require('./recommend');

const DIGESTS_DIR = path.join(__dirname, '..', 'digests');

// Topic-set classification. First match wins. Order matters.
const CATEGORY_MATCHERS = [
  { id: 'claude-code', label: '🤖 Claude Code', topics: ['claude-code', 'claude'] },
  { id: 'mcp', label: '🔌 MCP (Model Context Protocol)', topics: ['mcp', 'model-context-protocol'] },
  { id: 'adk', label: '🛠️  ADK / Agent SDK', topics: ['adk', 'agent-development-kit', 'agent-sdk'] },
  { id: 'agent-fw', label: '🧠 Agent Frameworks', topics: ['agent-framework', 'ai-agents', 'multi-agent', 'autogen', 'langgraph', 'crewai'] },
  { id: 'video-ai', label: '🎬 Video / Generative UI', topics: ['remotion', 'video-generation', 'generative-ui', 'animation'] },
  { id: 'rag', label: '📚 RAG / Retrieval', topics: ['rag', 'retrieval', 'embeddings', 'vector-database'] },
  { id: 'eval', label: '📏 Evaluation / Tooling', topics: ['llm-evaluation', 'llm-tools', 'llm-ops', 'prompt-engineering'] },
];

function classify(item) {
  const meta = parseMeta(item);
  const repoTopics = (meta.topics || []).map((t) => String(t).toLowerCase());
  const description = (item.description || '').toLowerCase();
  const title = (item.title || '').toLowerCase();

  if (meta.category_hint) {
    const found = CATEGORY_MATCHERS.find((c) => c.id === meta.category_hint);
    if (found) return found;
  }

  for (const cat of CATEGORY_MATCHERS) {
    for (const t of cat.topics) {
      if (repoTopics.includes(t) || description.includes(t) || title.includes(t)) {
        return cat;
      }
    }
  }
  return { id: 'other', label: '✨ Other', topics: [] };
}


function isRisingStar(item) {
  const meta = parseMeta(item);
  if (!meta.created_at) return false;
  const ageDays = (Date.now() - new Date(meta.created_at).getTime()) / 86400000;
  return ageDays <= 90 && (item.stars || 0) >= 200 && (item.stars || 0) < 5000;
}

function renderItem(item) {
  const meta = parseMeta(item);
  const stars = (item.stars || 0).toLocaleString();
  const reason = meta.match_reason || meta.perplexity_summary || meta.discovery_strategy || '';
  const lang = meta.language ? ` · ${meta.language}` : '';
  const desc = (item.description || '').replace(/\s+/g, ' ').trim().slice(0, 200);
  return `- **[${item.title}](${item.url})** · ${stars}★${lang}\n  - ${desc}${desc ? '\n  - ' : ''}_${reason}_`;
}

function renderTLDR(items) {
  const top = items.slice(0, 5);
  if (top.length === 0) return '_No items met the star floor this week._';
  return top
    .map((it, i) => {
      const stars = (it.stars || 0).toLocaleString();
      return `${i + 1}. **[${it.title}](${it.url})** — ${stars}★`;
    })
    .join('\n');
}

function buildDigestStructure({ items, runDate }) {
  const buckets = {};
  for (const cat of CATEGORY_MATCHERS) buckets[cat.id] = { cat, items: [] };
  buckets.other = { cat: { id: 'other', label: '✨ Other', topics: [] }, items: [] };

  const rising = [];
  for (const item of items) {
    const cat = classify(item);
    buckets[cat.id]?.items.push(item);
    if (isRisingStar(item)) rising.push(item);
  }

  const perCategory = {};
  for (const id of Object.keys(buckets)) {
    perCategory[id] = buckets[id].items.length;
  }

  return {
    buckets,
    rising,
    runDate,
    totals: {
      totalItems: items.length,
      perCategory,
      risingCount: rising.length,
    },
  };
}

function formatDigest({ items, runDate, channelStats = {} }) {
  const { buckets, rising } = buildDigestStructure({ items, runDate });

  const lines = [];
  lines.push(`# Weekly Claude Code Ecosystem Digest — ${runDate}`);
  lines.push('');
  lines.push(`> Items first seen in the last 7 days, filtered by star floor (≥1,000★ established / ≥200★ rising-star <90d).`);
  lines.push(`> Generated by AI Intelligence Hub — ${items.length} items across ${Object.values(buckets).filter((b) => b.items.length).length} categories.`);
  lines.push('');

  if (Object.keys(channelStats).length) {
    lines.push('**Channels run**: ' + Object.entries(channelStats).map(([k, v]) => `${k} (${v})`).join(' · '));
    lines.push('');
  }

  // TL;DR top 5
  lines.push('## TL;DR — Top 5');
  lines.push('');
  lines.push(renderTLDR(items));
  lines.push('');

  // Rising stars sub-section (always show, even if empty — signals the channel exists)
  lines.push('## 🌟 Rising Stars (last 90d, 200-5000★)');
  lines.push('');
  if (rising.length === 0) {
    lines.push('_No rising stars surfaced this week._');
  } else {
    for (const item of rising.slice(0, 8)) lines.push(renderItem(item));
  }
  lines.push('');

  // Per-category lists
  for (const cat of CATEGORY_MATCHERS) {
    const list = buckets[cat.id].items;
    if (list.length === 0) continue;
    lines.push(`## ${cat.label} (${list.length})`);
    lines.push('');
    for (const item of list) lines.push(renderItem(item));
    lines.push('');
  }

  // Other bucket only if non-trivial
  if (buckets.other.items.length > 0) {
    lines.push(`## ✨ Other (${buckets.other.items.length})`);
    lines.push('');
    for (const item of buckets.other.items) lines.push(renderItem(item));
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Star floor enforced. Generated ${new Date().toISOString()}._`);
  return lines.join('\n');
}

/**
 * Per-project section: top-N hardened recommendations for every project in
 * config/projects.json (same ranking as /api/recommendations, in-process).
 */
function formatProjectSections({ perProject = 5 } = {}) {
  let projects = [];
  try {
    projects = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'config', 'projects.json'), 'utf-8')).projects || [];
  } catch {
    return '';
  }
  const lines = ['', '## 🎯 Per-project suggestions (star floor 200, no forks/dupes)', ''];
  const pool = loadPool(db); // one read + parse for all projects
  for (const p of projects) {
    let recs;
    try {
      recs = recommendFromPool(pool, p.id, { limit: perProject });
    } catch (err) {
      lines.push(`### ${p.name} — error: ${err.message}`, '');
      continue;
    }
    lines.push(`### ${p.name} (${recs.discoveries.length} of ${recs.poolSize} candidates)`);
    if (!recs.discoveries.length) lines.push('- _no candidates above the floor yet_');
    for (const r of recs.discoveries) {
      const why = (r.relevance && r.relevance.matchReason) || '';
      lines.push(`- **[${r.title}](${r.url})** · ${(r.stars || 0).toLocaleString()}★${why ? ` — _${why}_` : ''}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

async function generateDigest({ channelStats = {}, costUsd = 0, runtimeStartMs = Date.now() } = {}) {
  if (!fs.existsSync(DIGESTS_DIR)) fs.mkdirSync(DIGESTS_DIR, { recursive: true });

  const runDate = new Date().toISOString().slice(0, 10);
  const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString();

  const items = db.getItemsFirstSeenSince(sevenDaysAgo, { limit: 80 });
  const md = formatDigest({ items, runDate, channelStats }) + formatProjectSections();

  const outPath = path.join(DIGESTS_DIR, `weekly-${runDate}.md`);
  fs.writeFileSync(outPath, md, 'utf-8');

  const runtimeMs = Date.now() - runtimeStartMs;
  db.insertWeeklyRun({
    run_date: runDate,
    item_count: items.length,
    channels_run: Object.keys(channelStats).join(','),
    runtime_ms: runtimeMs,
    cost_usd: costUsd,
  });

  return { digestPath: outPath, itemCount: items.length, runtimeMs };
}

module.exports = { generateDigest, formatDigest, formatProjectSections, buildDigestStructure, classify, isRisingStar, parseMeta };
